export const SESSION_STORAGE_KEYS = {
  JWT_TOKEN: "jwtToken",
  USERNAME: "username",
};

export const KEY_DOWN_IDS = {
  KEY_ENTER: 13,
};

export const CHAT_TYPES = {
  GROUP: "GROUP",
  PRIVATE: "PRIVATE",
};

export const SOCKET_MESSAGE_TYPES = {
  CHAT_MESSAGE: "CHAT_MESSAGE",
  CONVERSATION_OPEN: "CONVERSATION_OPEN",
  CONVERSATION_CREATED: "CONVERSATION_CREATED",
};

export const DEBOUNCE_INTERVAL = 500;
